import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { HomeNav } from "./components/homeNav/homeNav";
import { HomeSidebar } from "./components/homeNav/homeSidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative bg-[#FAFAFA]">
        <HomeSidebar />
       <HomeNav />
      
      {children}</body>
    </html>
  );
}
