
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css"
import {DashboardNav} from "./dashboard-components/dashboardNav";
import { DashboardSidebar } from "./dashboard-components/dashboardSidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative bg-[#FAFAFA] px-4 xl:px-14 2xl:px-32 py-4">
       <DashboardNav />
       <DashboardSidebar />
      {children}</body>
    </html>
  );
}
